"""Static registry of every ERP table managed by the AI agent.

The registry is derived from the SQL migrations in
``front-desk-app/supabase/migrations``. It is used to:
* validate table / column names before they reach PostgREST,
* give the agent a compact schema reference it can inspect at runtime.

Column values are kept short: ``type — short meaning``.
"""

import json
import os

TABLES: dict[str, dict] = {
    # ------------------------------------------------------------------ Org
    "users": {
        "schema": "public",
        "module": "Org",
        "description": "ERP users (id usually matches auth.users.id).",
        "columns": {
            "id": "uuid PK",
            "department_id": "uuid FK -> departments",
            "username": "text not null",
            "password_hash": "text",
            "email": "text",
            "phone": "text",
            "role": "text - admin|designer|front_desk|machine_operator|finish|marketer|admin_marketer|finance|creative",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "files": {
        "schema": "public",
        "module": "Org",
        "description": "File metadata (documents storage).",
        "columns": {
            "id": "uuid PK",
            "name": "text not null",
            "path": "text not null",
            "mime_type": "text",
            "file_size": "bigint",
            "uploaded_by": "uuid FK -> users",
            "description": "text",
            "uploaded_at": "timestamptz default now()",
        },
    },
    "notifications": {
        "schema": "public",
        "module": "Org",
        "description": "System notifications delivered per department/user.",
        "columns": {
            "id": "uuid PK",
            "department_id": "uuid FK -> departments",
            "title": "text not null",
            "body": "text",
            "icon": "text",
            "color": "text",
            "priority": "text default 'normal'",
            "category": "text default 'general'",
            "entity_type": "text",
            "entity_id": "uuid",
            "created_at": "timestamptz default now()",
        },
    },
    "read_notifications": {
        "schema": "public",
        "module": "Org",
        "description": "Per-user read state of notifications.",
        "columns": {
            "id": "uuid PK",
            "user_id": "uuid FK -> users",
            "notification_id": "uuid FK -> notifications",
            "is_read": "bool default false",
            "read_at": "timestamptz",
        },
    },
    "messages": {
        "schema": "public",
        "module": "Org",
        "description": "Internal user-to-user chat messages.",
        "columns": {
            "id": "uuid PK",
            "sender_id": "uuid FK -> users",
            "receiver_id": "uuid FK -> users",
            "text": "text",
            "is_read": "bool default false",
            "attached_file_ids": "uuid[]",
            "attached_files": "text[]",
            "sent_at": "timestamptz",
            "created_at": "timestamptz default now()",
        },
    },
    "notes": {
        "schema": "public",
        "module": "Org",
        "description": "User notes / checklists attached to any entity.",
        "columns": {
            "id": "uuid PK",
            "user_id": "uuid FK -> users",
            "entity_type": "text",
            "entity_id": "uuid",
            "title": "text",
            "content": "text",
            "color": "text",
            "pinned": "bool default false",
            "checklist": "jsonb",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    # -------------------------------------------------------------- CRM
    "clients": {
        "schema": "public",
        "module": "CRM",
        "description": "Unified leads + clients (customer master data).",
        "columns": {
            "id": "uuid PK",
            "client_type": "text - lead|client",
            "name": "text not null - display name",
            "company_name": "text",
            "phone": "text",
            "email": "text",
            "alt_email": "text",
            "address": "text",
            "city": "text",
            "subcity": "text",
            "woreda": "text",
            "region": "text",
            "po_box": "text",
            "type": "text - Corporate|Individual|Government",
            "industry": "text",
            "website": "text",
            "description": "text",
            "point_of_contact": "text",
            "priority": "text",
            "source": "text",
            "source_heard": "text",
            "budget": "numeric",
            "timeframe": "text",
            "interests": "jsonb",
            "assigned_sales_officer_id": "uuid FK -> users",
            "followup_date": "date",
            "tin": "text",
            "vat_number": "text",
            "reg_number": "text",
            "date_established": "date",
            "credit_limit": "numeric default 0",
            "payment_terms": "text",
            "currency": "text default 'ETB'",
            "opening_balance": "numeric default 0",
            "total_orders": "integer default 0",
            "total_sales": "numeric default 0",
            "paid_amount": "numeric default 0",
            "loyalty_level": "text",
            "account_manager": "text",
            "referral_source": "text",
            "status": "text default 'New' - New|Active|Inactive|Converted|Lost|Prospective",
            "registered_on": "date",
            "converted_at": "timestamptz",
            "document_file_ids": "uuid[]",
            "allow_self_update": "bool default false",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "client_contacts": {
        "schema": "public",
        "module": "CRM",
        "description": "Contact persons of a client.",
        "columns": {
            "id": "uuid PK",
            "client_id": "uuid FK -> clients",
            "name": "text not null",
            "phone": "text",
            "email": "text",
            "role": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "site_visits": {
        "schema": "public",
        "module": "CRM",
        "description": "Site visit requests/scheduling.",
        "columns": {
            "id": "uuid PK",
            "client_id": "uuid FK -> clients",
            "request_no": "text",
            "visit_purpose": "text",
            "city": "text",
            "detailed_address": "text",
            "requested_date": "date",
            "preferred_date": "date",
            "preferred_time": "time",
            "requested_by": "text",
            "department_id": "uuid FK -> departments",
            "installation_team": "text",
            "contact_person": "text",
            "phone": "text",
            "email": "text",
            "equipment_review": "text",
            "special_instructions": "text",
            "status": "text default 'Pending' - Pending|Scheduled|In Progress|Completed|Cancelled",
            "priority": "text default 'Medium' - High|Medium|Low",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    # --------------------------------------------------------------- Items
    "items": {
        "schema": "public",
        "module": "CRM",
        "description": "Catalog of sellable products/services with per-unit quantities.",
        "columns": {
            "id": "uuid PK",
            "name": "text not null",
            "pcs": "numeric default 0",
            "kilo": "numeric default 0",
            "care": "numeric default 0",
            "liter": "numeric default 0",
            "meter": "numeric default 0",
            "pack": "numeric default 0",
            "gram": "numeric default 0",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    # ------------------------------------------------------------- Orders
    "orders": {
        "schema": "public",
        "module": "Sales",
        "description": "Customer orders (header).",
        "columns": {
            "id": "uuid PK",
            "client_id": "uuid FK -> clients",
            "order_no": "text",
            "order_date": "date",
            "required_date": "date",
            "status": "text default 'New' - New|In Progress|In Production|Completed|Cancelled",
            "priority": "text default 'Medium' - High|Medium|Low",
            "total_amount": "numeric default 0",
            "paid_amount": "numeric default 0",
            "balance": "numeric default 0",
            "reference_po": "text",
            "sales_officer_id": "uuid FK -> users",
            "department_id": "uuid FK -> departments",
            "currency": "text default 'ETB'",
            "payment_terms": "text",
            "special_instructions": "text",
            "attachments": "uuid[]",
            "sales_type": "text - from_design|direct_sales",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "order_items": {
        "schema": "public",
        "module": "Sales",
        "description": "Line items of an order.",
        "columns": {
            "id": "uuid PK",
            "order_id": "uuid FK -> orders",
            "item_id": "uuid FK -> items",
            "quantity": "numeric default 1",
            "description": "text",
            "unit": "text",
            "unit_price": "numeric default 0",
            "discount_percent": "numeric default 0",
            "tax_percent": "numeric default 0",
            "amount": "numeric default 0",
            "created_at": "timestamptz default now()",
        },
    },
    "designs": {
        "schema": "public",
        "module": "Design",
        "description": "Design tasks attached to orders.",
        "columns": {
            "id": "uuid PK",
            "order_id": "uuid FK -> orders",
            "design_type": "text",
            "purpose": "text",
            "requested_date": "date",
            "required_date": "date",
            "priority": "text default 'Medium' - High|Medium|Low",
            "status": "text default 'Pending' - Pending|In Progress|Completed|Cancelled",
            "assigned_designer_id": "uuid FK -> users",
            "requested_by": "text",
            "brief_dimensions": "text",
            "specifications": "text",
            "special_instructions": "text",
            "attached_file_ids": "uuid[]",
            "internal_notes": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "design_versions": {
        "schema": "public",
        "module": "Design",
        "description": "Design revision history / sent versions.",
        "columns": {
            "id": "uuid PK",
            "design_id": "uuid FK -> designs",
            "file_id": "uuid FK -> files",
            "version_number": "integer not null",
            "description": "text",
            "sent_on": "timestamptz",
            "sent_by": "text",
            "status": "text default 'Sent' - Sent|Reviewed|Approved|Rejected",
            "comment": "text",
            "created_at": "timestamptz default now()",
        },
    },
    "design_communications": {
        "schema": "public",
        "module": "Design",
        "description": "Front-desk <-> designer messages about a design.",
        "columns": {
            "id": "uuid PK",
            "design_id": "uuid FK -> designs",
            "sender_id": "uuid FK -> users",
            "receiver_id": "uuid FK -> users",
            "message": "text not null",
            "is_read": "bool default false",
            "read_at": "timestamptz",
            "attached_file_ids": "uuid[]",
            "created_at": "timestamptz default now()",
        },
    },
    "warranties": {
        "schema": "public",
        "module": "Sales",
        "description": "Warranty claims.",
        "columns": {
            "id": "uuid PK",
            "order_id": "uuid FK -> orders",
            "order_item_id": "uuid FK -> order_items",
            "client_id": "uuid FK -> clients",
            "product_name": "text",
            "serial_no": "text",
            "purchase_date": "date",
            "warranty_expiry": "date",
            "defect_description": "text",
            "attachments": "uuid[]",
            "claim_type": "text",
            "assigned_to": "text",
            "resolution": "text",
            "status": "text default 'New' - New|In Progress|Approved|Rejected|Closed",
            "filed_at": "timestamptz",
            "closed_at": "timestamptz",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    # ------------------------------------------------------------ Invoicing
    "invoices": {
        "schema": "public",
        "module": "Sales",
        "description": "Proforma / Sales invoices (header).",
        "columns": {
            "id": "uuid PK",
            "order_id": "uuid FK -> orders",
            "invoice_no": "text",
            "invoice_type": "text - Proforma|Sales Invoice",
            "issue_date": "date",
            "due_date": "date",
            "reference": "text",
            "subtotal": "numeric default 0",
            "vat_amount": "numeric default 0",
            "grand_total": "numeric default 0",
            "paid_amount": "numeric default 0",
            "balance": "numeric default 0",
            "status": "text default 'Unpaid' - Unpaid|Paid|Partially Paid|Pending",
            "payment_method": "text",
            "bank_name": "text",
            "receipt_issued": "bool default false",
            "receipt_date": "date",
            "attached_file_ids": "uuid[]",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "invoice_items": {
        "schema": "public",
        "module": "Sales",
        "description": "Line items of an invoice.",
        "columns": {
            "id": "uuid PK",
            "invoice_id": "uuid FK -> invoices",
            "item_id": "uuid FK -> items",
            "description": "text",
            "quantity": "numeric default 1",
            "unit_price": "numeric default 0",
            "total": "numeric default 0",
            "created_at": "timestamptz default now()",
        },
    },
    "payments": {
        "schema": "public",
        "module": "Sales",
        "description": "Payments received against invoices.",
        "columns": {
            "id": "uuid PK",
            "invoice_id": "uuid FK -> invoices",
            "client_id": "uuid FK -> clients",
            "payment_date": "date",
            "amount_paid": "numeric default 0",
            "gross_amount": "numeric default 0",
            "unpaid_amount": "numeric default 0",
            "payment_method": "text - Cash|Bank Transfer|Mobile Money|Card|Credit|E-commerce",
            "bank_wallet": "text",
            "reference_number": "text",
            "received_by": "text",
            "invoice_status": "text - Unpaid|Paid|Partially Paid",
            "processing_status": "text - Requires Payment Method|Requires Action|Processing|Requires Capture|Succeeded|Failed|Canceled",
            "attached_file_ids": "uuid[]",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "job_orders": {
        "schema": "public",
        "module": "Production",
        "description": "Production job orders generated from invoices.",
        "columns": {
            "id": "uuid PK",
            "invoice_id": "uuid FK -> invoices",
            "job_no": "text",
            "collaboration": "text",
            "order_status": "text default 'Pending' - Pending|Started|Completed",
            "start_time": "timestamptz",
            "delivery_time": "timestamptz",
            "expected_date": "date",
            "follow_up": "text",
            "delivery_status": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "deliveries": {
        "schema": "public",
        "module": "Production",
        "description": "Deliveries for job orders.",
        "columns": {
            "id": "uuid PK",
            "job_order_id": "uuid FK -> job_orders",
            "client_id": "uuid FK -> clients",
            "delivery_no": "text",
            "company": "text",
            "delivery_address": "text",
            "contact_person": "text",
            "contact_phone": "text",
            "items": "text",
            "vehicle_driver": "text",
            "scheduled_date": "date",
            "scheduled_time": "time",
            "actual_delivery_time": "timestamptz",
            "status": "text default 'Pending' - Pending|In Transit|Delivered|Delayed",
            "received_by": "text",
            "logged_by": "text",
            "attached_file_ids": "uuid[]",
            "note": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "installations": {
        "schema": "public",
        "module": "Production",
        "description": "Installations for job orders.",
        "columns": {
            "id": "uuid PK",
            "job_order_id": "uuid FK -> job_orders",
            "client_id": "uuid FK -> clients",
            "installation_no": "text",
            "site_address": "text",
            "contact_person": "text",
            "contact_phone": "text",
            "items_installed": "text",
            "team": "text",
            "team_lead": "text",
            "scheduled_date": "date",
            "scheduled_time": "time",
            "completion_time": "timestamptz",
            "status": "text default 'Scheduled' - Scheduled|In Progress|Completed|Cancelled",
            "signed_off_by": "text",
            "logged_by": "text",
            "attached_file_ids": "uuid[]",
            "note": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "feedbacks": {
        "schema": "public",
        "module": "CRM",
        "description": "Customer feedback.",
        "columns": {
            "id": "uuid PK",
            "order_id": "uuid FK -> orders",
            "client_id": "uuid FK -> clients",
            "overall_rating": "text - Excellent|Good|Average|Poor",
            "delivery_rating": "text",
            "quality_rating": "text",
            "staff_service_rating": "text",
            "recommend": "text - Yes|No",
            "comments": "text",
            "submitted_at": "timestamptz",
            "created_at": "timestamptz default now()",
        },
    },
    "complaints": {
        "schema": "public",
        "module": "CRM",
        "description": "Customer complaints.",
        "columns": {
            "id": "uuid PK",
            "order_id": "uuid FK -> orders",
            "client_id": "uuid FK -> clients",
            "order_ref": "text",
            "category": "text",
            "severity": "text",
            "subject": "text",
            "description": "text",
            "attachments": "uuid[]",
            "assigned_to": "text",
            "resolution": "text",
            "status": "text default 'New' - New|In Progress|Resolved|Closed",
            "sla_breached": "bool default false",
            "logged_at": "timestamptz",
            "resolved_at": "timestamptz",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "test_proforma_invoices": {
        "schema": "public",
        "module": "Sales",
        "description": "Legacy proforma invoices (drafting/upgrade flow).",
        "columns": {
            "id": "uuid PK",
            "invoice_no": "text not null unique",
            "order_no": "text",
            "client_name": "text not null",
            "subtotal": "numeric default 0",
            "vat_amount": "numeric default 0",
            "vat_percentage": "numeric default 15",
            "grand_total": "numeric default 0",
            "apply_vat": "bool default true",
            "items": "jsonb",
            "status": "text default 'not_upgraded' - not_upgraded|upgraded",
            "attached_file_ids": "uuid[]",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    # ------------------------------------------------------------ Production
    "machines": {
        "schema": "public",
        "module": "Production",
        "description": "Machine registry.",
        "columns": {
            "id": "uuid PK",
            "name": "text not null",
            "machine_type": "text not null",
            "model": "text",
            "serial_number": "text",
            "location": "text",
            "status": "text default 'active' - active|maintenance|inactive",
            "purchased_date": "date",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "machine_maintenance_checklists": {
        "schema": "public",
        "module": "Production",
        "description": "Maintenance checklists per machine.",
        "columns": {
            "id": "uuid PK",
            "machine_id": "uuid FK -> machines",
            "checklist_type": "text - daily|weekly|monthly",
            "checklist_name": "text not null",
            "description": "text",
            "checklist_items": "jsonb",
            "estimated_duration": "integer (minutes)",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "machine_maintenance_logs": {
        "schema": "public",
        "module": "Production",
        "description": "Executed maintenance records.",
        "columns": {
            "id": "uuid PK",
            "checklist_id": "uuid FK -> machine_maintenance_checklists",
            "machine_id": "uuid FK -> machines",
            "performed_by": "uuid FK -> users",
            "performed_at": "timestamptz default now()",
            "checklist_results": "jsonb",
            "notes": "text",
            "status": "text default 'completed' - completed|partial|skipped",
            "created_at": "timestamptz default now()",
        },
    },
    "production_orders": {
        "schema": "public",
        "module": "Production",
        "description": "Manufacturing / production orders.",
        "columns": {
            "id": "uuid PK",
            "order_id": "uuid FK -> orders",
            "designer_id": "uuid FK -> users",
            "machine_id": "uuid FK -> machines",
            "material": "text",
            "thickness": "text",
            "color": "text",
            "length": "text",
            "width": "text",
            "height": "text",
            "gram": "text",
            "quality_status": "text - Pass|Fail|Pending",
            "completed_at": "timestamptz",
            "area": "numeric",
            "task_type": "text - project|task",
            "priority": "text default 'Medium' - High|Medium|Low",
            "status": "text default 'New' - New|In Progress|Completed|Cancelled",
            "job_type": "text - received|rework",
            "started_at": "timestamptz",
            "rework_reason": "text",
            "attached_file_ids": "uuid[]",
            "note": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    # ------------------------------------------------------------- Inventory
    "inventory": {
        "schema": "public",
        "module": "Inventory",
        "description": "Stock master.",
        "columns": {
            "id": "uuid PK",
            "item_code": "text unique",
            "name": "text not null",
            "category": "text",
            "description": "text",
            "unit_of_measure": "text",
            "current_quantity": "numeric default 0",
            "minimum_stock": "numeric default 0",
            "location": "text",
            "status": "text default 'active' - active|inactive",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "inventory_movements": {
        "schema": "public",
        "module": "Inventory",
        "description": "Stock in/out transactions.",
        "columns": {
            "id": "uuid PK",
            "inventory_id": "uuid FK -> inventory",
            "movement_type": "text - in|out",
            "quantity": "numeric not null",
            "reference_type": "text",
            "reference_id": "uuid",
            "machine_id": "uuid FK -> machines",
            "production_order_id": "uuid FK -> production_orders",
            "performed_by": "uuid FK -> users",
            "notes": "text",
            "movement_date": "timestamptz default now()",
            "created_at": "timestamptz default now()",
        },
    },
    # -------------------------------------------------- Marketing v2 (mrkt_)
    "mrkt_plans": {
        "schema": "public",
        "module": "Marketing",
        "description": "Hierarchical marketing plans.",
        "columns": {
            "id": "uuid PK",
            "name": "text not null",
            "description": "text",
            "type": "text - annual|monthly|weekly|quarterly",
            "status": "text default 'draft' - draft|active|archived",
            "parent_plan_id": "uuid FK -> mrkt_plans",
            "start_date": "date",
            "end_date": "date",
            "target_revenue": "numeric(12,2) default 0",
            "target_leads": "integer default 0",
            "owner_id": "uuid FK -> users",
            "notes": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_campaigns": {
        "schema": "public",
        "module": "Marketing",
        "description": "Marketing campaigns.",
        "columns": {
            "id": "uuid PK",
            "name": "text not null",
            "description": "text",
            "status": "enum(planned|active|completed|on_hold|archived) default 'planned'",
            "start_date": "date",
            "end_date": "date",
            "budget_estimated": "numeric(12,2) default 0",
            "owner_id": "uuid FK -> users",
            "notes": "text",
            "plan_id": "uuid FK -> mrkt_plans",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_campaign_targets": {
        "schema": "public",
        "module": "Marketing",
        "description": "Campaign KPI targets.",
        "columns": {
            "id": "uuid PK",
            "campaign_id": "uuid FK -> mrkt_campaigns",
            "metric": "text not null",
            "target_value": "numeric(12,2)",
            "actual_value": "numeric(12,2) default 0",
            "target_date": "date",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_activities": {
        "schema": "public",
        "module": "Marketing",
        "description": "Marketing activity scheduling.",
        "columns": {
            "id": "uuid PK",
            "campaign_id": "uuid FK -> mrkt_campaigns",
            "title": "text not null",
            "type": "enum(content_production|social_media|website|paid_ad|visit|meeting|demo|event|follow_up|other)",
            "status": "enum(planned|in_progress|completed|overdue) default 'planned'",
            "scheduled_start": "timestamptz",
            "scheduled_end": "timestamptz",
            "completed_at": "timestamptz",
            "assigned_to": "uuid FK -> users",
            "location": "text",
            "notes": "text",
            "checklists": "jsonb",
            "attachments": "jsonb",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_proposals": {
        "schema": "public",
        "module": "Marketing",
        "description": "Client proposals.",
        "columns": {
            "id": "uuid PK",
            "campaign_id": "uuid FK -> mrkt_campaigns",
            "client_name": "text not null",
            "client_email": "text",
            "amount": "numeric(12,2) default 0",
            "status": "enum(draft|submitted|follow_up|accepted|rejected|on_hold) default 'draft'",
            "submitted_at": "timestamptz",
            "follow_up_at": "timestamptz",
            "accepted_at": "timestamptz",
            "owner_id": "uuid FK -> users",
            "file_url": "text",
            "notes": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_proformas": {
        "schema": "public",
        "module": "Marketing",
        "description": "Marketing proforma invoices.",
        "columns": {
            "id": "uuid PK",
            "campaign_id": "uuid FK -> mrkt_campaigns",
            "client_name": "text not null",
            "client_email": "text",
            "amount": "numeric(12,2) default 0",
            "status": "enum(requested|submitted|follow_up|accepted|rejected|on_hold) default 'requested'",
            "requested_at": "timestamptz",
            "submitted_at": "timestamptz",
            "accepted_at": "timestamptz",
            "owner_id": "uuid FK -> users",
            "file_url": "text",
            "notes": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_tenders": {
        "schema": "public",
        "module": "Marketing",
        "description": "Tender opportunities.",
        "columns": {
            "id": "uuid PK",
            "campaign_id": "uuid FK -> mrkt_campaigns",
            "title": "text not null",
            "client_name": "text",
            "amount": "numeric(12,2) default 0",
            "status": "enum(opportunity|preparation|submitted|follow_up|awarded|lost|on_hold) default 'opportunity'",
            "deadline": "date",
            "submitted_at": "timestamptz",
            "awarded_at": "timestamptz",
            "owner_id": "uuid FK -> users",
            "file_url": "text",
            "notes": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_products_services": {
        "schema": "public",
        "module": "Marketing",
        "description": "Marketing product/service catalog.",
        "columns": {
            "id": "uuid PK",
            "name": "text not null",
            "description": "text",
            "type": "text - product|service",
            "category": "text",
            "unit_cost": "numeric(12,2) default 0",
            "unit_price": "numeric(12,2) default 0",
            "sku": "text unique",
            "marketing": "text",
            "strategy": "text",
            "date": "date",
            "status": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_expenses": {
        "schema": "public",
        "module": "Marketing",
        "description": "Campaign expenses.",
        "columns": {
            "id": "uuid PK",
            "campaign_id": "uuid FK -> mrkt_campaigns",
            "category": "enum(advertising|content|events|travel|software|personnel|other)",
            "description": "text",
            "amount": "numeric(12,2) not null (>= 0)",
            "expense_date": "date not null",
            "receipt_url": "text",
            "submitted_by": "uuid FK -> users",
            "approved_by": "uuid FK -> users",
            "approval_status": "text default 'pending' - pending|approved|rejected",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_market_insights": {
        "schema": "public",
        "module": "Marketing",
        "description": "Market intelligence.",
        "columns": {
            "id": "uuid PK",
            "type": "enum(customer_need|competitor|market_trend|new_opportunity)",
            "title": "text not null",
            "description": "text",
            "source": "text",
            "date_identified": "date default current_date",
            "relevance_score": "int 1-10",
            "campaign_id": "uuid FK -> mrkt_campaigns",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "mrkt_proposal_items": {
        "schema": "public",
        "module": "Marketing",
        "description": "Proposal line items.",
        "columns": {
            "id": "uuid PK",
            "proposal_id": "uuid FK -> mrkt_proposals",
            "product_service_id": "uuid FK -> mrkt_products_services",
            "description": "text not null",
            "quantity": "integer default 1",
            "unit_price": "numeric(12,2) default 0",
            "total": "numeric(12,2) generated",
            "created_at": "timestamptz default now()",
        },
    },
    "mrkt_proforma_items": {
        "schema": "public",
        "module": "Marketing",
        "description": "Proforma line items.",
        "columns": {
            "id": "uuid PK",
            "proforma_id": "uuid FK -> mrkt_proformas",
            "product_service_id": "uuid FK -> mrkt_products_services",
            "description": "text not null",
            "quantity": "integer default 1",
            "unit_price": "numeric(12,2) default 0",
            "total": "numeric(12,2) generated",
            "created_at": "timestamptz default now()",
        },
    },
    # ----------------------------------------------------- Creative (crt_)
    "crt_prototype_requests": {
        "schema": "public",
        "module": "Creative",
        "description": "Prototype requests.",
        "columns": {
            "id": "uuid PK",
            "request_date": "date not null",
            "request_number": "text unique not null",
            "department": "text not null",
            "description": "text not null",
            "priority": "text default 'Normal' - Normal|High|Low",
            "deadline": "date not null",
            "assigned_technologist": "text not null",
            "status": "text default 'On Progress' - On Progress|Completed|Pending|Rejected",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "crt_idea_hub": {
        "schema": "public",
        "module": "Creative",
        "description": "Idea tracking.",
        "columns": {
            "id": "uuid PK",
            "idea_date": "date not null",
            "idea_code": "text unique not null",
            "title": "text not null",
            "source": "text not null",
            "priority": "text default 'Normal' - Normal|High",
            "target_date": "date not null",
            "estimated_cost": "numeric not null",
            "status": "text default 'Under Review' - Approved|Under Review|Pending|Rejected",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "crt_design_bom": {
        "schema": "public",
        "module": "Creative",
        "description": "Design and bill of materials.",
        "columns": {
            "id": "uuid PK",
            "design_date": "date not null",
            "design_reference": "text unique not null",
            "project_title": "text not null",
            "priority": "text default 'Normal' - Normal|High",
            "machine_routes": "text[] not null",
            "bom_item": "text not null",
            "bom_quantity": "integer default 1",
            "total_price": "numeric not null",
            "status": "text default 'Ready' - Ready|In Progress|Completed|Pending",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    "crt_staff_leaves": {
        "schema": "public",
        "module": "Creative",
        "description": "Creative staff leave management.",
        "columns": {
            "id": "uuid PK",
            "application_date": "date not null",
            "leave_id": "text unique not null",
            "employee_name": "text not null",
            "leave_from": "date not null",
            "leave_to": "date not null",
            "leave_type": "text - Annual Year Leave|Sick Medical Leave|Personal Casual Exception",
            "justification": "text not null",
            "status": "text default 'Under Review' - Under Review|Approved|Rejected|Cancelled",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
        },
    },
    # --------------------------------------------- Finance (public prefix)
    "finance_gl_accounts": {
        "schema": "public",
        "module": "Finance",
        "description": "Chart of accounts (public schema).",
        "columns": {
            "id": "uuid PK",
            "account_code": "varchar(20) unique not null",
            "account_name": "varchar(255) not null",
            "account_type": "enum(Asset|Liability|Equity|Revenue|Expense)",
            "parent_id": "uuid FK -> finance_gl_accounts",
            "description": "text",
            "is_active": "bool default true",
            "items": "jsonb default '[]'",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
            "created_by": "uuid",
            "updated_by": "uuid",
        },
    },
    "finance_purchases": {
        "schema": "public",
        "module": "Finance",
        "description": "Purchase records (public schema).",
        "columns": {
            "id": "uuid PK",
            "purchase_no": "varchar(50) unique not null",
            "purchase_type": "enum(Cash|Credit)",
            "seller_tin": "varchar(50)",
            "seller_name": "varchar(255) not null",
            "seller_id": "uuid",
            "purchase_date": "date not null",
            "receipt_source": "enum(Manual|FS)",
            "reference_no": "varchar(100)",
            "gl_account_id": "uuid FK -> finance_gl_accounts",
            "vat_type": "enum(VAT|Exempted)",
            "subtotal": "numeric(15,2) default 0",
            "vat_amount": "numeric(15,2) default 0",
            "total_amount": "numeric(15,2) default 0",
            "status": "varchar(50) default 'Draft'",
            "notes": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
            "created_by": "uuid",
            "updated_by": "uuid",
        },
    },
    "finance_purchase_items": {
        "schema": "public",
        "module": "Finance",
        "description": "Purchase line items (public schema).",
        "columns": {
            "id": "uuid PK",
            "purchase_id": "uuid FK -> finance_purchases",
            "item_id": "uuid",
            "item_name": "varchar(255) not null",
            "description": "text",
            "quantity": "numeric(15,2) not null",
            "unit_price": "numeric(15,2) not null",
            "total": "numeric(15,2) generated",
            "gl_account_id": "uuid FK -> finance_gl_accounts",
            "created_at": "timestamptz default now()",
        },
    },
    "finance_sales": {
        "schema": "public",
        "module": "Finance",
        "description": "Sales records (public schema).",
        "columns": {
            "id": "uuid PK",
            "sales_no": "varchar(50) unique not null",
            "sales_type": "enum(Cash|Credit)",
            "sales_category": "varchar(50) not null",
            "cash_received": "numeric(15,2) default 0",
            "customer_tin": "varchar(50)",
            "customer_name": "varchar(255) not null",
            "customer_id": "uuid",
            "sales_date": "date not null",
            "receipt_source": "enum(Manual|FS)",
            "vat_withholding": "enum(No Withholding|3%|7.5%|30%) default 'No Withholding'",
            "subtotal": "numeric(15,2) default 0",
            "vat_amount": "numeric(15,2) default 0",
            "withholding_amount": "numeric(15,2) default 0",
            "total_amount": "numeric(15,2) default 0",
            "net_amount": "numeric(15,2) default 0",
            "status": "varchar(50) default 'Draft'",
            "notes": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
            "created_by": "uuid",
            "updated_by": "uuid",
        },
    },
    "finance_sales_items": {
        "schema": "public",
        "module": "Finance",
        "description": "Sales line items (public schema).",
        "columns": {
            "id": "uuid PK",
            "sales_id": "uuid FK -> finance_sales",
            "item_id": "uuid",
            "item_name": "varchar(255) not null",
            "quantity": "numeric(15,2) not null",
            "unit_price": "numeric(15,2) not null",
            "tax_rate": "numeric(5,2) default 15.00",
            "total": "numeric(15,2) generated",
            "gl_account_id": "uuid FK -> finance_gl_accounts",
            "created_at": "timestamptz default now()",
        },
    },
    "finance_journals": {
        "schema": "public",
        "module": "Finance",
        "description": "General journals (public schema).",
        "columns": {
            "id": "uuid PK",
            "journal_no": "varchar(50) unique not null",
            "journal_date": "date not null",
            "reference": "varchar(100)",
            "description": "text",
            "status": "enum(Draft|Posted) default 'Draft'",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
            "created_by": "uuid",
            "updated_by": "uuid",
        },
    },
    "finance_journal_lines": {
        "schema": "public",
        "module": "Finance",
        "description": "Double-entry journal lines (public schema).",
        "columns": {
            "id": "uuid PK",
            "journal_id": "uuid FK -> finance_journals",
            "gl_account_id": "uuid FK -> finance_gl_accounts",
            "description": "text",
            "debit": "numeric(15,2) default 0",
            "credit": "numeric(15,2) default 0",
            "created_at": "timestamptz default now()",
        },
    },
    "finance_payroll": {
        "schema": "public",
        "module": "Finance",
        "description": "Payroll records (public schema).",
        "columns": {
            "id": "uuid PK",
            "employee_id": "uuid not null",
            "period_start": "date not null",
            "period_end": "date not null",
            "basic_salary": "numeric(15,2) default 0",
            "transport_allowance": "numeric(15,2) default 0",
            "telephone_allowance": "numeric(15,2) default 0",
            "overtime": "numeric(15,2) default 0",
            "other_earnings": "numeric(15,2) default 0",
            "gross_salary": "numeric(15,2) generated",
            "taxable_salary": "numeric(15,2) default 0",
            "income_tax": "numeric(15,2) default 0",
            "pension_employee": "numeric(15,2) default 0",
            "pension_employer": "numeric(15,2) default 0",
            "total_deductions": "numeric(15,2) default 0",
            "net_pay": "numeric(15,2) default 0",
            "status": "enum(Draft|Approved|Paid) default 'Draft'",
            "payment_date": "date",
            "notes": "text",
            "created_at": "timestamptz default now()",
            "updated_at": "timestamptz default now()",
            "created_by": "uuid",
            "updated_by": "uuid",
        },
    },
    "finance_tax_rates": {
        "schema": "public",
        "module": "Finance",
        "description": "Tax rates configuration (public schema).",
        "columns": {
            "id": "uuid PK",
            "tax_type": "varchar(50) not null",
            "rate": "numeric(5,2) not null",
            "effective_from": "date not null",
            "effective_to": "date",
            "is_active": "bool default true",
            "created_at": "timestamptz default now()",
        },
    },
    "finance_sync_log": {
        "schema": "public",
        "module": "Finance",
        "description": "Finance sync dedup log (public schema).",
        "columns": {
            "id": "uuid PK",
            "source_type": "varchar(50) not null",
            "source_id": "uuid not null",
            "sync_type": "varchar(50) not null",
            "synced_at": "timestamptz default now()",
            "period_start": "date",
            "period_end": "date",
            "status": "varchar(20) default 'success'",
            "error_message": "text",
            "created_at": "timestamptz default now()",
        },
    },
}

# Non-ERP tables reserved for the AI chat feature itself (not agent-managed).
RESERVED = {
    "ai_sessions",
    "ai_chats",
    "ai_attachments",
    "ai_attachment_chunks",
}

ALLOWED_OPS = {"eq", "neq", "gt", "gte", "lt", "lte", "like", "ilike", "in", "is", "contains"}

# The ERP roles defined in the `users` table. Access is granted per module.
ROLES = (
    "admin",
    "designer",
    "front_desk",
    "machine_operator",
    "finish",
    "marketer",
    "admin_marketer",
    "finance",
    "creative",
)

# role -> {module: "rw" | "read" | "none"}
# Adjust this dict to change which tables each role can see / edit. An optional
# ROLE_ACCESS_OVERRIDE env var (JSON, same shape) is layered on top so you can
# toggle visibility without touching code.
ROLE_DEFAULTS: dict[str, dict[str, str]] = {
    "admin": {
        "Org": "rw", "CRM": "rw", "Sales": "rw", "Design": "rw",
        "Production": "rw", "Inventory": "rw", "Marketing": "rw",
        "Finance": "read", "Creative": "rw",
    },
    "front_desk": {
        "Org": "read", "CRM": "rw", "Sales": "rw", "Design": "rw",
        "Production": "read", "Inventory": "read", "Marketing": "read",
        "Finance": "read", "Creative": "none",
    },
    "designer": {
        "Org": "read", "CRM": "read", "Sales": "read", "Design": "rw",
        "Production": "read", "Inventory": "read", "Marketing": "none",
        "Finance": "none", "Creative": "none",
    },
    "machine_operator": {
        "Org": "read", "CRM": "read", "Sales": "read", "Design": "read",
        "Production": "rw", "Inventory": "rw", "Marketing": "none",
        "Finance": "none", "Creative": "none",
    },
    "finish": {
        "Org": "read", "CRM": "read", "Sales": "read", "Design": "read",
        "Production": "rw", "Inventory": "read", "Marketing": "none",
        "Finance": "none", "Creative": "none",
    },
    "marketer": {
        "Org": "read", "CRM": "read", "Sales": "read", "Design": "none",
        "Production": "none", "Inventory": "none", "Marketing": "rw",
        "Finance": "read", "Creative": "none",
    },
    "admin_marketer": {
        "Org": "read", "CRM": "rw", "Sales": "read", "Design": "none",
        "Production": "none", "Inventory": "read", "Marketing": "rw",
        "Finance": "read", "Creative": "none",
    },
    "finance": {
        "Org": "read", "CRM": "read", "Sales": "read", "Design": "none",
        "Production": "none", "Inventory": "read", "Marketing": "read",
        "Finance": "rw", "Creative": "none",
    },
    "creative": {
        "Org": "read", "CRM": "none", "Sales": "read", "Design": "rw",
        "Production": "rw", "Inventory": "read", "Marketing": "none",
        "Finance": "none", "Creative": "rw",
    },
    "auditor": {
        "Org": "read", "CRM": "read", "Sales": "read", "Design": "read",
        "Production": "read", "Inventory": "read", "Marketing": "read",
        "Finance": "read", "Creative": "read",
    },
}


def _apply_role_override() -> None:
    """Layer ROLE_ACCESS_OVERRIDE (JSON) onto ROLE_DEFAULTS at import time."""
    raw = os.getenv("ROLE_ACCESS_OVERRIDE")
    if not raw:
        return
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        print("ROLE_ACCESS_OVERRIDE is not valid JSON; ignoring.")
        return
    for role, modules in parsed.items():
        if role in ROLE_DEFAULTS and isinstance(modules, dict):
            ROLE_DEFAULTS[role] = {**ROLE_DEFAULTS[role], **modules}


_apply_role_override()


def role_modules(role: str | None) -> dict[str, str]:
    """Module access map for a role; unknown/None roles are denied everything."""
    if role and role in ROLE_DEFAULTS:
        return ROLE_DEFAULTS[role]
    return {}


def access_level(role: str | None, table: str) -> str:
    """One of 'rw', 'read' or 'none' for a given role + module of a table."""
    module = require_table(table)["module"]
    return role_modules(role).get(module, "none")


def accessible_table_names(role: str | None) -> list[str]:
    """Tables the role can at least read, sorted by name."""
    allowed = role_modules(role)
    return sorted(
        name for name, info in TABLES.items() if allowed.get(info["module"], "none") != "none"
    )


def require_table(name: str) -> dict:
    """Return the table definition or raise ValueError with a helpful list."""
    if name not in TABLES:
        raise ValueError(
            f"Unknown table '{name}'. Know tables: {', '.join(sorted(TABLES))}"
        )
    return TABLES[name]


def table_schema(name: str) -> str:
    return require_table(name)["schema"]


def column_names(name: str) -> set[str]:
    return set(require_table(name)["columns"])


def validate_columns(name: str, cols: set[str]) -> None:
    known = column_names(name)
    bad = sorted(cols - known)
    if bad:
        raise ValueError(f"Unknown column(s) {bad} for table '{name}'")


def table_columns_description(name: str) -> str:
    info = require_table(name)
    lines = [f"{name} [{info['module']}] — {info['description']}"]
    for col, desc in info["columns"].items():
        lines.append(f"  {col}: {desc}")
    return "\n".join(lines)


def table_real_name(name: str) -> str:
    """Actual SQL table name (used by PostgREST) for a registered table."""
    return require_table(name).get("name", name)


def table_overview(role: str | None = None) -> str:
    """Compact one-line-per-table listing for the agent system prompt.

    When *role* is given only tables the role can read are listed.
    """
    allowed = role_modules(role) if role else None
    lines: list[str] = []
    for name in sorted(TABLES):
        info = TABLES[name]
        if allowed is not None and allowed.get(info["module"], "none") == "none":
            continue
        schema_prefix = "" if info["schema"] == "public" else f"{info['schema']}."
        lines.append(f"- {schema_prefix}{name} [{info['module']}]: {info['description']}")
    return "\n".join(lines)